const CLASSIFICATION_VERSION='deterministic-v1';
const IT_TITLE=[['frontend',6],['front end',6],['backend',6],['back end',6],['full stack',7],['fullstack',7],['software engineer',7],['software developer',7],['web developer',6],['react developer',7],['node.js developer',7],['devops',7],['cloud engineer',7],['data engineer',7],['data scientist',7],['machine learning',7],['qa engineer',6],['test engineer',6],['automation engineer',5],['cybersecurity',7],['security engineer',6],['mobile developer',6],['android developer',7],['ios developer',7],['ui developer',5],['product engineer',3],['application developer',6],['programmer',6]];
const NON_IT_TITLE=[['business development',8],['area sales',9],['sales manager',8],['sales executive',8],['marketing',8],['influencer',8],['customer service',8],['customer support',7],['key account manager',8],['account manager',7],['human resources',8],['hr executive',8],['recruiter',7],['talent acquisition',6],['finance',7],['accounting',7],['legal',7],['operations manager',6],['relationship manager',7],['field sales',8],['telecaller',8]];
const TECHNOLOGIES=['react','javascript','typescript','node.js','nodejs','express','mongodb','sql','python','java','c++','c#','aws','azure','docker','kubernetes','git','html','css','rest api','graphql','angular','vue','next.js','spring boot','django','.net','postgresql','mysql','redis','jenkins','terraform','linux','microservices','api development','software development','web application','source control'];
const NON_IT_EVIDENCE=['sales target','lead generation','dealer management','customer handling','cold calling','revenue target','market research','brand campaign','influencer marketing','client acquisition','account management','recruitment','payroll','bookkeeping','financial reporting','legal compliance','store visits','field sales','customer service','customer relationship'];
const SUBCATEGORIES={FRONTEND:['frontend','front end','react','angular','vue','javascript','typescript','html','css','ui developer'],BACKEND:['backend','back end','node.js','nodejs','express','spring boot','django','.net','api development','microservices'],FULL_STACK:['full stack','fullstack','front-end and back-end','frontend and backend'],MOBILE:['mobile developer','android','ios','react native','flutter','swift','kotlin'],DEVOPS_CLOUD:['devops','cloud engineer','aws','azure','docker','kubernetes','jenkins','terraform','ci/cd'],DATA_AI:['data engineer','data scientist','machine learning','artificial intelligence','python','pandas','tensorflow','pytorch'],QA_TESTING:['qa engineer','test engineer','automation engineer','quality assurance','selenium','cypress','jest'],CYBERSECURITY:['cybersecurity','security engineer','information security','penetration testing','soc analyst'],UI_UX:['ui/ux','ux designer','ui designer','product designer','figma'],SOFTWARE_ENGINEERING:['software engineer','software developer','product engineer','application developer','programmer']};
const clean=value=>String(value||'').toLowerCase().replace(/[^a-z0-9+#./ -]+/g,' ');
const has=(text,term)=>text.includes(term);
function scoreTerms(text,terms){return terms.reduce((score,[term,weight])=>score+(has(text,term)?weight:0),0)}
function classifyJob(job){
 const title=clean(job.title),skills=clean((job.skills||[]).join(' ')),description=clean(job.description),all=`${title} ${skills} ${description}`;
 const titleIt=scoreTerms(title,IT_TITLE),titleNon=scoreTerms(title,NON_IT_TITLE),skillHits=TECHNOLOGIES.filter(term=>has(skills,term)),descriptionTech=TECHNOLOGIES.filter(term=>has(description,term)),nonEvidence=NON_IT_EVIDENCE.filter(term=>has(all,term));
 let itScore=titleIt+skillHits.length*3+Math.min(descriptionTech.length,8)*1.25,nonScore=titleNon+Math.min(nonEvidence.length,6)*1.5;
 if(titleNon>=8&&skillHits.length===0&&descriptionTech.length<2)nonScore+=4;
 let category='UNKNOWN';if(itScore>=4&&itScore>nonScore*1.15)category='IT';else if(nonScore>=4&&nonScore>itScore*1.15)category='NON_IT';
 const total=Math.max(itScore+nonScore,1),margin=Math.abs(itScore-nonScore)/total,evidence=Math.min(Math.max(itScore,nonScore)/12,1),categoryConfidence=Math.round(Math.min(.99,.5+margin*.32+evidence*.17)*100)/100;
 let subcategory=null;if(category==='IT'){const scores=Object.entries(SUBCATEGORIES).map(([name,terms])=>[name,terms.reduce((score,term)=>score+(has(title,term)?4:has(skills,term)?3:has(description,term)?1:0),0)]).sort((a,b)=>b[1]-a[1]);subcategory=scores[0][1]>0?scores[0][0]:'OTHER_IT'}
 return{category,subcategory,categoryConfidence,classificationVersion:CLASSIFICATION_VERSION};
}
let backfillPromise=null;
async function backfillJobClassifications(Job){if(backfillPromise)return backfillPromise;backfillPromise=(async()=>{const jobs=await Job.find({classificationVersion:{$ne:CLASSIFICATION_VERSION}}).select('_id title skills description').lean();if(jobs.length)await Job.bulkWrite(jobs.map(job=>({updateOne:{filter:{_id:job._id},update:{$set:classifyJob(job)}}})),{ordered:false});return jobs.length})().finally(()=>{backfillPromise=null});return backfillPromise}
module.exports={CLASSIFICATION_VERSION,classifyJob,backfillJobClassifications};
