const crypto=require('crypto');
const mongoose=require('mongoose');
const Application=require('../models/Application');
const Event=require('../models/ApplicationEvent');
const Job=require('../models/Job');
const httpError=require('../utils/httpError');
const {notify}=require('../services/notificationService');
const statusTypes={Prepared:'APPLICATION_CREATED',Queued:'AUTO_APPLY_QUEUED',Applied:'APPLICATION_CREATED','Application Received':'APPLICATION_RECEIVED',Assessment:'ASSESSMENT',Interview:'INTERVIEW',Offer:'OFFER',Rejected:'REJECTION',Failed:'AUTO_APPLY_FAILED','Needs Review':'AUTO_APPLY_NEEDS_REVIEW',Withdrawn:'WITHDRAWN'};
const manualTypes=['APPLICATION_RECEIVED','ASSESSMENT','INTERVIEW_INVITATION','INTERVIEW_SCHEDULED','INTERVIEW','OFFER','REJECTION','RECRUITER_CONTACT','EMAIL_UPDATE'];
const valid=id=>{if(!mongoose.isValidObjectId(id))throw httpError(400,'Invalid identifier')};

exports.create=async(req,res)=>{valid(req.body.jobId);const job=await Job.findById(req.body.jobId);if(!job)throw httpError(404,'Job not found');if(await Application.exists({userId:req.userId,jobId:req.body.jobId}))throw httpError(409,'This job is already in your applications');const confirmed=req.body.submissionConfirmed===true,submittedAt=confirmed?new Date():null;let application=await Application.create({userId:req.userId,jobId:req.body.jobId,status:confirmed?'Applied':'Prepared',appliedAt:submittedAt,submittedAt,source:'MANUAL',submissionMethod:'MANUAL',applicationUrl:job.originalUrl,nextAction:req.body.nextAction||'',nextActionDate:req.body.nextActionDate,notes:req.body.notes||''});await Event.create({applicationId:application._id,type:'APPLICATION_CREATED',source:'system',timestamp:submittedAt||new Date(),title:confirmed?'Applied':'Application tracked',description:confirmed?'User confirmed that the target application system accepted the submission.':'Job added for tracking; submission has not been confirmed.',dedupeKey:'application-created'});application=await application.populate('jobId');res.status(201).json({success:true,message:confirmed?'Application marked as applied':'Application added for tracking as Prepared',data:application,application})};
exports.list=async(req,res)=>{const filter={userId:req.userId};if(req.query.status)filter.status=req.query.status;const applications=await Application.find(filter).populate('jobId').sort({createdAt:-1});res.json({success:true,message:'Applications fetched successfully',data:applications,count:applications.length,applications})};
exports.getOne=async(req,res)=>{valid(req.params.id);const application=await Application.findOne({_id:req.params.id,userId:req.userId}).populate('jobId');if(!application)throw httpError(404,'Application not found');res.json({success:true,message:'Application fetched successfully',data:application,application})};
exports.update=async(req,res)=>{valid(req.params.id);const allowed=['status','nextAction','nextActionDate','notes'],update=Object.fromEntries(Object.entries(req.body).filter(([key])=>allowed.includes(key)));const before=await Application.findOne({_id:req.params.id,userId:req.userId});if(!before)throw httpError(404,'Application not found');const application=await Application.findByIdAndUpdate(before._id,update,{returnDocument:"after",runValidators:true}).populate('jobId');if(update.status&&update.status!==before.status){await Event.create({applicationId:before._id,type:statusTypes[update.status],source:'manual',timestamp:new Date(),title:`Status changed to ${update.status}`,description:'Application status updated manually.',metadata:{from:before.status,to:update.status}});await notify(req.userId,{type:'APPLICATION_STATUS_CHANGED',title:'Application status changed',message:`${application.jobId?.title||'Application'} moved from ${before.status} to ${update.status}.`,relatedApplication:application._id,relatedJob:application.jobId?._id,dedupeKey:`application-status:${application._id}:${update.status}`})}res.json({success:true,message:'Application updated successfully',data:application,application})};
exports.events=async(req,res)=>{valid(req.params.id);if(!await Application.exists({_id:req.params.id,userId:req.userId}))throw httpError(404,'Application not found');const documents=await Event.find({applicationId:req.params.id}).sort({timestamp:1,createdAt:1}).lean(),events=documents.map(event=>({...event,timestamp:event.timestamp||event.createdAt}));res.json({success:true,message:'Application events fetched successfully',data:events,events})};
exports.addEvent=async(req,res)=>{valid(req.params.id);if(!await Application.exists({_id:req.params.id,userId:req.userId}))throw httpError(404,'Application not found');const type=String(req.body.type||'').toUpperCase(),title=String(req.body.title||'').trim(),description=String(req.body.description||'').trim();if(!manualTypes.includes(type))throw httpError(400,'Invalid timeline event type');if(!title)throw httpError(400,'Event title is required');const timestamp=req.body.timestamp?new Date(req.body.timestamp):new Date();if(Number.isNaN(timestamp.getTime()))throw httpError(400,'Invalid event timestamp');const suppliedKey=String(req.body.idempotencyKey||'').trim(),dedupeKey=suppliedKey?crypto.createHash('sha256').update(`${req.userId}:${suppliedKey}`).digest('hex'):undefined;if(dedupeKey){const existing=await Event.findOne({applicationId:req.params.id,dedupeKey});if(existing)return res.json({success:true,message:'Timeline event already exists',data:existing,event:existing,duplicate:true})}else{const recent=await Event.findOne({applicationId:req.params.id,source:'manual',type,title,description,createdAt:{$gte:new Date(Date.now()-300000)}});if(recent)return res.json({success:true,message:'Duplicate timeline event ignored',data:recent,event:recent,duplicate:true})}const event=await Event.create({applicationId:req.params.id,type,title,description,source:'manual',timestamp,metadata:req.body.metadata&&typeof req.body.metadata==='object'?req.body.metadata:{},dedupeKey});res.status(201).json({success:true,message:'Application event created',data:event,event})};
