const Job=require('../models/Job'),Saved=require('../models/SavedJob'),Application=require('../models/Application');
const Profile=require('../models/Profile'),{analyzeSkillGaps,summarizeDashboardInsights}=require('../services/ai/aiService'),httpError=require('../utils/httpError');
const ApplicationEvent=require('../models/ApplicationEvent'),JobMatch=require('../models/JobMatch'),AutoApplyDraft=require('../models/AutoApplyDraft');
const {PERSONAL_USER_ID}=require('../utils/user');
exports.summary=async(req,res)=>{const applications=await Application.find({userId:req.userId}).select('_id status'),ids=applications.map(item=>item._id);const[newMatches,savedJobs,activeJobs,rejections,drafts]=await Promise.all([Job.countDocuments({isActive:true,expiredAt:null}),Saved.countDocuments({userId:req.userId}),Job.countDocuments({isActive:true,expiredAt:null,staleAt:{$gt:new Date()}}),ApplicationEvent.countDocuments({applicationId:{$in:ids},type:'REJECTION'}),AutoApplyDraft.find({userId:req.userId}).select('status applicationId')]),counts=applications.reduce((out,item)=>(out[item.status]=(out[item.status]||0)+1,out),{}),draftCounts=drafts.reduce((out,item)=>(out[item.status]=(out[item.status]||0)+1,out),{}),autoIds=drafts.map(item=>item.applicationId).filter(Boolean),autoResponses=await Application.countDocuments({_id:{$in:autoIds},status:{$in:['Assessment','Interview','Offer']}}),data={newMatches,savedJobs,activeJobs,totalApplications:applications.length,applied:counts.Applied||0,assessments:counts.Assessment||0,interviews:counts.Interview||0,offers:counts.Offer||0,rejections,autoApply:{prepared:(draftCounts.Prepared||0)+(draftCounts.Reviewed||0)+(draftCounts.Applied||0),reviewed:(draftCounts.Reviewed||0)+(draftCounts.Applied||0),applied:draftCounts.Applied||0,responses:autoResponses,interviews:await Application.countDocuments({_id:{$in:autoIds},status:{$in:['Interview','Offer']}})}};res.json({success:true,message:'Dashboard summary fetched successfully',data,...data})};
exports.matches=async(req,res)=>{const jobs=await Job.find().sort({postedAt:-1,createdAt:-1}).limit(10);res.json({success:true,message:'Recent matches fetched successfully',data:jobs,jobs})};
exports.recent=async(req,res)=>{const applications=await Application.find({userId:req.userId}).populate('jobId').sort({createdAt:-1}).limit(10);res.json({success:true,message:'Recent applications fetched successfully',data:applications,applications})};
exports.insights=async(req,res)=>{
  const userId=req.userId;
  const[profile,applications]=await Promise.all([Profile.findOne({userId}),Application.find({userId}).populate('jobId')]);
  const applicationJobs=applications.map(item=>item.jobId).filter(Boolean);
  const jobs=applicationJobs.length?applicationJobs:await Job.find().sort({postedAt:-1,createdAt:-1}).limit(50);
  const profileSkills=new Set([...(profile?.skills||[]),...(profile?.technologies||[])].map(value=>String(value).trim().toLowerCase()));
  const skillCounts=new Map(),roleStats=new Map(),locationCounts=new Map();
  for(const job of jobs){
    const uniqueSkills=[...new Set((job.skills||[]).map(value=>String(value).trim()).filter(Boolean))];
    for(const skill of uniqueSkills){const key=skill.toLowerCase(),current=skillCounts.get(key)||{skill,count:0};current.count+=1;skillCounts.set(key,current)}
    if(job.location)locationCounts.set(job.location,(locationCounts.get(job.location)||0)+1);
    if(job.title){const matched=uniqueSkills.filter(skill=>profileSkills.has(skill.toLowerCase())).length,ratio=uniqueSkills.length?matched/uniqueSkills.length:0,current=roleStats.get(job.title)||{role:job.title,score:0,matchedSkills:0,jobs:0,locations:new Map()};current.score=Math.max(current.score,ratio);current.matchedSkills=Math.max(current.matchedSkills,matched);current.jobs+=1;if(job.location)current.locations.set(job.location,(current.locations.get(job.location)||0)+1);roleStats.set(job.title,current)}
  }
  const requestedSkills=[...skillCounts.values()].sort((a,b)=>b.count-a.count||a.skill.localeCompare(b.skill));
  const roles=[...roleStats.values()].sort((a,b)=>b.score-a.score||b.matchedSkills-a.matchedSkills||b.jobs-a.jobs||a.role.localeCompare(b.role));
  const best=profileSkills.size&&roles.length?roles[0]:null,topLocation=best?[...best.locations.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]:null;
  const active=applications.filter(item=>item.status!=='Withdrawn'),responses=active.filter(item=>['Assessment','Interview','Offer'].includes(item.status)).length,interviews=active.filter(item=>['Interview','Offer'].includes(item.status)).length;
  const mostRequestedSkill=requestedSkills[0]||null,potentialSkill=requestedSkills.find(item=>!profileSkills.has(item.skill.toLowerCase()))||null;
  const applicationIds=applications.map(item=>item._id),jobIds=applicationJobs.map(job=>job._id),rejections=await ApplicationEvent.countDocuments({applicationId:{$in:applicationIds},type:'REJECTION'}),matches=jobIds.length?await JobMatch.aggregate([{$match:{userId,jobId:{$in:jobIds},'result.score':{$type:'number'}}},{$sort:{generatedAt:-1}},{$group:{_id:'$jobId',score:{$first:'$result.score'}}}]):[];
  const countBy=value=>[...value.entries()].map(([label,count])=>({label,count})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label)),inc=(map,key)=>{if(key)map.set(key,(map.get(key)||0)+1)},months=new Map(),statuses=new Map(),companies=new Map(),appliedRoles=new Map(),appliedLocations=new Map();for(const application of applications){inc(statuses,application.status);inc(months,new Date(application.appliedAt).toISOString().slice(0,7));inc(companies,application.jobId?.company);inc(appliedRoles,application.jobId?.title);inc(appliedLocations,application.jobId?.location)}
  const metrics={dataBasis:applicationJobs.length?'applications':'available jobs',analyzedJobs:jobs.length,bestMatchingRole:best?{role:best.role,matchedSkills:best.matchedSkills,jobCount:best.jobs}:null,mostRequestedSkill,potentialSkillToImprove:potentialSkill,suggestedFocus:best?`${best.role}${topLocation?` roles in ${topLocation}`:' roles'}`:null,applicationResponseRate:{percentage:active.length?Math.round(responses/active.length*100):null,numerator:responses,denominator:active.length},interviewConversion:{percentage:active.length?Math.round(interviews/active.length*100):null,numerator:interviews,denominator:active.length},totalApplications:applications.length,withdrawnApplications:applications.length-active.length,rejections,applicationsByMonth:countBy(months),applicationsByStatus:countBy(statuses),topCompanies:countBy(companies).slice(0,10),topRoles:countBy(appliedRoles).slice(0,10),topLocations:countBy(appliedLocations).slice(0,10),averageAppliedMatchScore:matches.length?Math.round(matches.reduce((sum,item)=>sum+item.score,0)/matches.length):null};
  let aiSummary=null,aiSummaryCached=false,aiSummaryGeneratedAt=null;try{const ai=await summarizeDashboardInsights(metrics,userId);aiSummary=ai.summary;aiSummaryCached=ai.cached;aiSummaryGeneratedAt=ai.generatedAt}catch(error){if(![429,502,503,504].includes(error.statusCode))throw error}
  const data={...metrics,aiSummary,aiSummaryCached,aiSummaryGeneratedAt};res.json({success:true,message:'Dashboard insights fetched successfully',data,...data});
};
exports.skills=async(req,res)=>{const userId=req.userId||PERSONAL_USER_ID,profile=await Profile.findOne({userId});if(!profile)throw httpError(404,'Complete your profile before running skill gap analysis');const roleTerms=[...(profile.preferredRoles||[]),...(profile.jobTitles||[])].filter(Boolean).slice(0,6),locationTerms=(profile.preferredLocations||[]).filter(Boolean).slice(0,4);const safeRegex=value=>String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const preference=[];if(roleTerms.length)preference.push({title:{$regex:roleTerms.map(safeRegex).join('|'),$options:'i'}});if(locationTerms.length)preference.push({location:{$regex:locationTerms.map(safeRegex).join('|'),$options:'i'}});let jobs=preference.length?await Job.find({$or:preference,description:{$ne:''}}).sort({postedAt:-1,createdAt:-1}).limit(15):[];if(jobs.length<5)jobs=await Job.find({description:{$ne:''}}).sort({postedAt:-1,createdAt:-1}).limit(15);const data=await analyzeSkillGaps(jobs,profile,userId),count=field=>Object.entries(jobs.reduce((out,job)=>(out[String(job[field]||'Unknown')]=(out[String(job[field]||'Unknown')]||0)+1,out),{})).map(([label,total])=>({label,count:total,percentage:Math.round(total/jobs.length*100)})).sort((a,b)=>b.count-a.count),extra={targetRoles:profile.preferredRoles||[],popularLocations:count('location'),commonCompanies:count('company'),experienceRequirements:count('experience'),jobTypes:count('jobType'),workModes:count('workMode')};const result={...data,...extra};res.json({success:true,message:'Skill gap analysis fetched successfully',data:result,...result})};
