import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import Sidebar from './sidebar';
import { Notice, formatDate } from './ApiState';
import { addApplicationEvent, getApplicationById, getApplicationEvents } from '../services/api';

const eventTypes=[['APPLICATION_RECEIVED','Application Received'],['ASSESSMENT','Assessment'],['INTERVIEW_INVITATION','Interview Invitation'],['INTERVIEW_SCHEDULED','Interview Scheduled'],['INTERVIEW','Interview'],['OFFER','Offer'],['REJECTION','Rejection'],['RECRUITER_CONTACT','Recruiter Contact'],['EMAIL_UPDATE','Other Update']];
const iconFor=type=>({APPLICATION_CREATED:'send',APPLICATION_RECEIVED:'mark_email_read',ASSESSMENT:'assignment',INTERVIEW_INVITATION:'event',INTERVIEW_SCHEDULED:'calendar_month',INTERVIEW:'forum',OFFER:'celebration',REJECTION:'mail',RECRUITER_CONTACT:'person',EMAIL_UPDATE:'mail'}[type]||'circle');
const formatTimestamp=value=>value?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Date unavailable';

export default function ApplicationDetails(){
  const{id}=useParams(),[application,setApplication]=useState(null),[events,setEvents]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[form,setForm]=useState({type:'APPLICATION_RECEIVED',title:'Application Received',description:'',timestamp:''});
  useEffect(()=>{Promise.all([getApplicationById(id),getApplicationEvents(id)]).then(([app,timeline])=>{setApplication(app.data||app.application);setEvents(timeline.data||timeline.events||[])}).catch(err=>setError(err.message)).finally(()=>setLoading(false))},[id]);
  function changeType(type){const label=eventTypes.find(item=>item[0]===type)?.[1]||'';setForm(current=>({...current,type,title:label}))}
  async function submit(event){event.preventDefault();setSaving(true);setMessage('');try{const result=await addApplicationEvent(id,{...form,idempotencyKey:crypto.randomUUID()});const item=result.data||result.event;setEvents(current=>[...current,item].sort((a,b)=>new Date(a.timestamp||a.createdAt)-new Date(b.timestamp||b.createdAt)));setMessage(result.duplicate?'That event was already on the timeline.':'Timeline event added.');setForm({type:'APPLICATION_RECEIVED',title:'Application Received',description:'',timestamp:''})}catch(err){setMessage(err.message)}finally{setSaving(false)}}
  if(loading)return <main className="min-h-screen md:ml-sidebar-width bg-background"><Sidebar/><div className="p-margin-page"><Notice>Loading application timeline...</Notice></div></main>;
  if(error||!application)return <main className="min-h-screen md:ml-sidebar-width bg-background"><Sidebar/><div className="p-margin-page"><Notice error>{error||'Application not found'}</Notice></div></main>;
  const job=application.jobId||{};
  return <main className="min-h-screen md:ml-sidebar-width bg-background"><Sidebar/><header className="h-16 sticky top-0 z-40 bg-surface border-b border-outline-variant flex items-center px-margin-page"><Link to="/applications" className="flex items-center gap-2 text-on-surface-variant hover:text-primary"><span className="material-symbols-outlined">arrow_back</span>Applications</Link></header><div className="p-4 md:p-margin-page max-w-container-max mx-auto space-y-6"><section className="bg-surface rounded-xl border border-outline-variant p-6"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-on-surface-variant">Application Details</p><h2 className="font-headline-lg text-headline-lg">{job.title}</h2><p className="text-on-surface-variant">{job.company} · {job.location}</p></div><span className="h-fit px-4 py-2 rounded-full bg-primary-container text-on-primary-container font-medium">{application.status}</span></div><div className="grid sm:grid-cols-3 gap-4 mt-6 text-sm"><div><p className="text-on-surface-variant">Applied</p><p>{formatDate(application.appliedAt)}</p></div><div><p className="text-on-surface-variant">Next action</p><p>{application.nextAction||'None scheduled'}</p></div><div><p className="text-on-surface-variant">Next action date</p><p>{formatDate(application.nextActionDate)}</p></div></div></section>
    {message&&<Notice>{message}</Notice>}
    <div className="grid lg:grid-cols-3 gap-gutter"><section className="lg:col-span-2 bg-surface rounded-xl border border-outline-variant p-6"><h3 className="font-title-lg text-title-lg mb-6">Application Timeline</h3>{events.length===0?<Notice>No timeline events yet.</Notice>:<ol>{events.map((item,index)=><li key={item._id} className="relative flex gap-4 pb-8 last:pb-0"><div className="relative z-10 w-10 h-10 rounded-full bg-primary-container text-primary flex items-center justify-center shrink-0"><span className="material-symbols-outlined text-xl">{iconFor(item.type)}</span></div>{index<events.length-1&&<div className="absolute left-5 top-10 bottom-0 w-px bg-outline-variant"/>}<div className="pt-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><h4 className="font-semibold">{item.title}</h4><span className="px-2 py-0.5 rounded-full bg-surface-container-low text-xs capitalize">{item.source}</span></div><p className="text-sm text-on-surface-variant">{formatTimestamp(item.timestamp||item.createdAt)}</p>{item.description&&<p className="mt-2 text-sm">{item.description}</p>}{item.source==='gmail'&&item.metadata?.sender&&<p className="mt-1 text-xs text-on-surface-variant">From: {item.metadata.sender}</p>}</div></li>)}</ol>}</section>
      <aside className="bg-surface rounded-xl border border-outline-variant p-6 h-fit"><h3 className="font-title-lg text-title-lg mb-4">Add timeline event</h3><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">Event type<select value={form.type} onChange={event=>changeType(event.target.value)} className="block w-full mt-1 rounded-lg border-outline-variant">{eventTypes.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm font-medium">Title<input required maxLength="160" value={form.title} onChange={event=>setForm(current=>({...current,title:event.target.value}))} className="block w-full mt-1 rounded-lg border border-outline-variant px-3 py-2"/></label><label className="block text-sm font-medium">Description<textarea maxLength="2000" rows="3" value={form.description} onChange={event=>setForm(current=>({...current,description:event.target.value}))} className="block w-full mt-1 rounded-lg border border-outline-variant px-3 py-2"/></label><label className="block text-sm font-medium">Date and time<input type="datetime-local" value={form.timestamp} onChange={event=>setForm(current=>({...current,timestamp:event.target.value}))} className="block w-full mt-1 rounded-lg border border-outline-variant px-3 py-2"/></label><button disabled={saving} className="w-full rounded-lg bg-primary text-white px-4 py-2 disabled:opacity-60">{saving?'Adding...':'Add Event'}</button><p className="text-xs text-on-surface-variant">Manual events are labeled as manual. Gmail and system sources cannot be selected here.</p></form></aside>
    </div></div></main>;
}
