import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import Sidebar from './sidebar';
import { Notice, formatDate } from './ApiState';
import { createApplication, getDashboardApplications, getDashboardInsights, getDashboardMatches, getDashboardSummary, getSkillGapAnalysis } from '../services/api';

export default function Dashboard(){
  const [summary,setSummary]=useState({}),[jobs,setJobs]=useState([]),[apps,setApps]=useState([]),[skills,setSkills]=useState({}),[insights,setInsights]=useState({}),[skillError,setSkillError]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('');
  useEffect(()=>{const skillRequest=getSkillGapAnalysis().catch(e=>{setSkillError(e.message);return null});Promise.all([getDashboardSummary(),getDashboardMatches(),getDashboardApplications(),getDashboardInsights(),skillRequest]).then(([s,m,a,i,k])=>{setSummary(s.data||s);setJobs(m.data||m.jobs||[]);setApps(a.data||a.applications||[]);setInsights(i.data||i);if(k)setSkills(k.data||k)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
  async function apply(id){try{await createApplication(id);setMessage('Application added successfully.')}catch(e){setMessage(e.status===409?'You have already added this job to your applications.':e.message)}}
  const cards=[['Applications',summary.totalApplications||0,'send'],['Saved Jobs',summary.savedJobs||0,'bookmark'],['Active Jobs',summary.activeJobs||0,'work'],['Interviews',summary.interviews||0,'forum'],['Offers',summary.offers||0,'celebration'],['Rejections',summary.rejections||0,'cancel']];
  const insightCards=[['Best matching role',insights.bestMatchingRole?.role],['Most requested skill',insights.mostRequestedSkill?.skill],['Potential skill to improve',insights.potentialSkillToImprove?.skill],['Application response rate',insights.applicationResponseRate?.percentage==null?null:`${insights.applicationResponseRate.percentage}%`],['Interview conversion',insights.interviewConversion?.percentage==null?null:`${insights.interviewConversion.percentage}%`]];
  return <div className="min-h-screen bg-background md:pl-sidebar-width"><Sidebar/><header className="h-16 sticky top-0 bg-surface border-b border-outline-variant flex items-center px-margin-page font-title-lg">Overview</header><main className="p-4 md:p-margin-page max-w-container-max mx-auto"><h2 className="font-headline-lg text-headline-lg">Your job search overview</h2><p className="text-on-surface-variant mb-6">Latest job matches and application insights.</p>{error?<Notice error>{error}</Notice>:loading?<Notice>Loading dashboard...</Notice>:<>{message&&<div className="mb-4"><Notice>{message}</Notice></div>}
    <section className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 mb-6">{cards.map(([title,value,icon])=><div key={title} className="bg-surface rounded-xl p-4 border border-outline-variant"><div className="flex justify-between text-xs uppercase text-on-surface-variant"><span>{title}</span><span className="material-symbols-outlined text-primary">{icon}</span></div><div className="font-display-lg text-display-lg mt-2">{value}</div></div>)}</section>
    <section className="bg-surface rounded-xl border border-outline-variant p-5 mb-6"><div className="flex justify-between items-center mb-3"><h3 className="font-title-lg text-title-lg">Auto Apply</h3><Link to="/auto-apply" className="text-primary text-sm">Review applications</Link></div><div className="grid grid-cols-2 sm:grid-cols-5 gap-3">{[['Prepared',summary.autoApply?.prepared],['Reviewed',summary.autoApply?.reviewed],['Applied',summary.autoApply?.applied],['Responses',summary.autoApply?.responses],['Interviews',summary.autoApply?.interviews]].map(([label,value])=><div key={label} className="bg-surface-container-low rounded-lg p-3"><p className="text-xs text-on-surface-variant">{label}</p><p className="font-title-lg text-title-lg">{value||0}</p></div>)}</div></section>
    <section className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4 mb-6">{insightCards.map(([label,value])=><div key={label} className="bg-surface rounded-xl border border-outline-variant p-4"><p className="text-xs uppercase text-on-surface-variant">{label}</p><p className="font-title-md text-title-md mt-2">{value||'Not enough data'}</p></div>)}</section>
    {(insights.suggestedFocus||insights.aiSummary)&&<section className="bg-surface rounded-xl border border-outline-variant p-5 mb-6"><h3 className="font-title-lg text-title-lg mb-2">Suggested focus</h3>{insights.suggestedFocus&&<p>{insights.suggestedFocus}</p>}{insights.aiSummary&&<p className="text-sm text-on-surface-variant mt-2">{insights.aiSummary}</p>}<p className="text-xs text-on-surface-variant mt-3">Based on {insights.analyzedJobs} {insights.dataBasis}.</p></section>}
    <section className="grid md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">{[['Average applied match',insights.averageAppliedMatchScore==null?'Not enough data':`${insights.averageAppliedMatchScore}%`],['Top company',insights.topCompanies?.[0]?.label],['Top role',insights.topRoles?.[0]?.label],['Top location',insights.topLocations?.[0]?.label]].map(([label,value])=><div key={label} className="bg-surface rounded-xl border border-outline-variant p-4"><p className="text-xs uppercase text-on-surface-variant">{label}</p><p className="font-semibold mt-2">{value||'Not enough data'}</p></div>)}</section>
    <div className="grid lg:grid-cols-3 gap-gutter"><section className="lg:col-span-2 bg-surface rounded-xl border border-outline-variant p-5"><div className="flex justify-between mb-4"><h3 className="font-title-lg text-title-lg">Top Matches</h3><Link to="/find-jobs" className="text-primary">View all</Link></div>{jobs.length===0?<Notice>No recent job matches available.</Notice>:<div className="space-y-3">{jobs.slice(0,5).map(j=><div key={j._id} className="flex flex-wrap justify-between items-center gap-3 p-4 rounded-lg border border-outline-variant"><div><Link to={`/jobs/${j._id}`} className="font-semibold hover:text-primary">{j.title}</Link><p className="text-sm text-on-surface-variant">{j.company} · {j.location}</p></div><button onClick={()=>apply(j._id)} className="bg-primary text-white rounded-lg px-4 py-2">Apply</button></div>)}</div>}</section>
      <section className="bg-surface rounded-xl border border-outline-variant p-5"><div className="flex justify-between mb-4"><h3 className="font-title-lg text-title-lg">Common Skills</h3><Link to="/skills" className="text-primary text-sm">Details</Link></div><p className="text-xs text-on-surface-variant mb-2">Frequently requested in your selected jobs.</p>{skillError?<p className="text-sm text-error">Analysis unavailable: {skillError}</p>:(skills.commonSkills||[]).slice(0,6).map(item=><div key={item.skill} className="flex justify-between border-b border-outline-variant py-2"><span>{item.skill}</span><span>{item.percentage}%</span></div>)}</section></div>
    <section className="mt-6 bg-surface rounded-xl border border-outline-variant p-5"><h3 className="font-title-lg text-title-lg mb-4">Recent Applications</h3>{apps.length===0?<Notice>No recent applications.</Notice>:apps.slice(0,5).map(a=><div key={a._id} className="flex justify-between py-3 border-b border-outline-variant"><span>{a.jobId?.title} · {a.jobId?.company}</span><span className="text-on-surface-variant">{a.status} · {formatDate(a.appliedAt)}</span></div>)}</section>
  </>}</main></div>;
}
