import { useEffect, useState } from 'react';
import Sidebar from './sidebar';
import { Notice } from './ApiState';
import { getSkillGapAnalysis } from '../services/api';

export default function Skills() {
  const [analysis,setAnalysis]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{getSkillGapAnalysis().then(result=>setAnalysis(result.data||result)).catch(err=>setError(err.message)).finally(()=>setLoading(false))},[]);
  const common=analysis?.commonSkills||[],gaps=analysis?.potentialGaps||[],userSkills=analysis?.userSkills||[];
  return <div className="flex-1 flex flex-col min-h-screen md:pl-sidebar-width"><Sidebar/>
    <header className="w-full h-16 flex items-center px-margin-page sticky top-0 z-40 bg-surface border-b border-outline-variant shrink-0"><h1 className="font-title-lg text-title-lg">Skills &amp; Insights</h1></header>
    <main className="flex-1 bg-background p-margin-page"><div className="max-w-container-max mx-auto space-y-8">
      <section><h2 className="font-headline-lg text-headline-lg font-bold text-on-surface tracking-tight">Skills &amp; Insights</h2><p className="font-body-lg text-body-lg text-on-surface-variant">Compare your profile with skills explicitly mentioned across relevant jobs.</p></section>
      {loading?<Notice>Analyzing relevant jobs with Gemini...</Notice>:error?<Notice error>{error}</Notice>:<div className="grid grid-cols-1 lg:grid-cols-3 gap-gutter">
        <div className="lg:col-span-2 space-y-gutter">
          <section className="bg-surface-container-lowest rounded-xl border border-outline-variant p-6 shadow-[0_4px_12px_rgba(0,0,0,0.02)]"><h3 className="font-title-lg text-title-lg mb-6 flex items-center gap-2"><span className="material-symbols-outlined text-primary">star</span>Your Skills</h3>{userSkills.length?<div className="flex flex-wrap gap-3">{userSkills.map(skill=><span key={skill} className="px-4 py-2 bg-surface-container-low text-primary-fixed-variant rounded-lg border border-primary-fixed text-label-md font-semibold flex items-center gap-1"><span className="material-symbols-outlined text-sm">check</span>{skill}</span>)}</div>:<Notice>No skills are saved in your profile yet.</Notice>}</section>
          <section className="bg-surface-container-lowest rounded-xl border border-outline-variant p-6 shadow-[0_4px_12px_rgba(0,0,0,0.02)]"><h3 className="font-title-lg text-title-lg mb-2 flex items-center gap-2"><span className="material-symbols-outlined text-secondary">troubleshoot</span>Potential Skill Gaps</h3><p className="text-sm text-on-surface-variant mb-5">{analysis.disclaimer}</p>{gaps.length?<div className="overflow-x-auto"><table className="w-full text-left border-collapse"><thead><tr className="border-b border-outline-variant"><th className="pb-3 text-label-md text-on-surface-variant uppercase">Skill</th><th className="pb-3 text-label-md text-on-surface-variant uppercase">Selected jobs</th><th className="pb-3 text-label-md text-on-surface-variant uppercase">Interpretation</th></tr></thead><tbody className="divide-y divide-outline-variant/50">{gaps.map(item=><tr key={item.skill}><td className="py-4 font-medium">{item.skill}</td><td className="py-4"><div className="flex items-center gap-2"><div className="w-24 h-2 bg-surface-variant rounded-full overflow-hidden"><div className="h-full bg-primary" style={{width:`${item.percentage}%`}}/></div><span>{item.percentage}%</span></div></td><td className="py-4 text-on-surface-variant">{item.note}</td></tr>)}</tbody></table></div>:<Notice>No potential gaps were identified from the selected jobs.</Notice>}</section>
        </div>
        <aside className="bg-surface-container-lowest rounded-xl border border-outline-variant p-6 h-fit shadow-[0_4px_12px_rgba(0,0,0,0.02)]"><h3 className="font-title-lg text-title-lg mb-2 flex items-center gap-2"><span className="material-symbols-outlined text-primary">trending_up</span>Commonly Requested</h3><p className="text-sm text-on-surface-variant mb-6">Based on {analysis.analyzedJobs} relevant jobs.</p>{common.length?<div className="space-y-4">{common.slice(0,10).map(item=><div key={item.skill}><div className="flex justify-between text-sm mb-1"><span className="font-medium">{item.skill}</span><span className="text-on-surface-variant">{item.percentage}%</span></div><div className="w-full h-2 bg-surface-variant rounded-full overflow-hidden"><div className="h-full bg-primary rounded-r-full" style={{width:`${item.percentage}%`}}/></div></div>)}</div>:<Notice>No explicit skills were found.</Notice>}<p className="mt-6 pt-4 border-t border-outline-variant text-xs text-on-surface-variant">{analysis.cached?'Cached analysis':'New analysis'} · Generated {new Date(analysis.generatedAt).toLocaleString()}</p></aside>
      </div>}
      {analysis&&<section className="bg-surface-container-lowest rounded-xl border border-outline-variant p-6"><h3 className="font-title-lg text-title-lg mb-5">Job Market Insights</h3><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{[['Target roles',(analysis.targetRoles||[]).map(label=>({label}))],['Popular locations',analysis.popularLocations],['Common companies',analysis.commonCompanies],['Experience requirements',analysis.experienceRequirements],['Job types',analysis.jobTypes],['Work modes',analysis.workModes]].map(([title,items])=><div key={title}><h4 className="font-semibold mb-2">{title}</h4>{items?.length?<ul className="space-y-1 text-sm text-on-surface-variant">{items.slice(0,5).map((item,index)=><li key={`${item.label}-${index}`} className="flex justify-between gap-3"><span>{item.label}</span>{item.percentage!=null&&<span>{item.percentage}%</span>}</li>)}</ul>:<p className="text-sm text-on-surface-variant">Not enough data</p>}</div>)}</div></section>}
    </div></main>
  </div>;
}
